### ISSUE TITLE
[ Week 7 ] 7주차 워크북 미션1,2,3

### ISSUE THREAD

**Issue by heeone1** [DS-UMC-7th/UMC-7th-Wonie#19]
### 🛠 Mission

1.  Project에 useQuery 를 활용하기
2.  Project에 useInfiniteQuery 를 활용하기
3. Pagination 기능 구현

### 📝 To-do

1.  Project에 useQuery 를 활용하기
- [x]  지금까지, **`custom-hook`**을 활용하여, 불러온 `get 요청`의 데이터들을 먼저 **`useQuery`** 를 활용한 데이터 호출로 변경해주세요.
- [x] queryKey를 명확하게 설정
- [x] useQuery의 반환 값을 활용하여, loading과 error 처리를 진행
- [x] 로딩 처리는 Skeleton UI를 활용

2. Project에 useInfiniteQuery 를 활용하기
- [x]  지금까지, 미션 1에서 **`useQuery`**를 활용하여, 불러온 `get 요청`의 데이터들을 먼저 **`useInfiniteQuery`** 를 활용한 데이터 호출로 변경해주세요.
- [x] queryKey를 명확하게 설정
- [x] useQuery의 반환 값을 활용하여, loading과 error 처리를 진행
- [x] 로딩 처리는 `Skeleton UI`를 활용해주세요.
- [x]  `Loading Spinner` 또한 활용

4. Pagination 기능 구현
- [x] Pagination을 구현
- [x] 0 page는 데이터가 존재하지 않으므로, 사용자가 0 page를 가지 못하게, Button을 disabled 처리
- [x] queryKey를 명확하게 설정

### 🔍 접근 방법

- useQuery 
- useInfiniteQuery 
- Pagination
