### ISSUE TITLE
[ Week 8 ] 1주차 워크북 미션

### ISSUE THREAD

**Issue by heeone1** [DS-UMC-7th/UMC-7th-Wonie#21]
### 🛠 Mission

미션 1. ToDo List 구현 (useEffect 활용)
미션 2. ToDoList 구현 (Tanstack-Query 활용)

### 📝 To-do

미션 1. ToDo List 구현 (useEffect 활용)
- [ ]  http://localhost:3000/doc 에서, **`swagger`**를 통해, 서버 통신을 활용하여, 개발을 진행해보세요.
- [ ]  **`custom-fetch-hook`**을 만들어 사용하였는가?
- [ ]  **`컴포넌트 분리`**를 잘 진행했는가?
- [ ]  **`Styled-Components`**를 활용하여, 스타일링을 멋있게 진행했는가?
- [ ]  **`useEffect`**를 활용하여, API 통신을 진행해주세요!
- [ ]  `로딩`, `에러처리`, `버튼의 Disabled` 처리를 진행해주세요!

미션 2. ToDoList 구현 (Tanstack-Query 활용)
- [ ]  `GET` 요청 시 `useQuery`를 활용
    - [ ]  `queryKey` 설정을 잘 하였는가?
- [ ]  `POST`, `DELETE`, `PATCH` 요청시, **`useMutation`**을 활용

### 🔍 접근 방법

- useEffect 
- Tanstack-Query
