### ISSUE TITLE
[ Week 8 ] 8주차 워크북 미션3

### ISSUE THREAD

**Issue by heeone1** [DS-UMC-7th/UMC-7th-Wonie#22]
### 🛠 Mission

미션 3. 기존, 영화 사이트 리팩토링

### 📝 To-do

- [x]  `POST` 요청시, **`useMutation`**을 활용한 코드로 리팩토링
    - [x]  `회원가입 api`를 `useMutation`을 활용한 코드로 수정해주세요!
    - [x]  `로그인 api`를 `useMutation`을 활용한 코드로 수정해주세요!
- [x]  https://watcha.com/ 홈페이지를 보며, 본인의 프로젝트의 완성도를 높여주세요.
    - [x]  2개의 페이지 이상 최대한 비슷하게 따라 만들어서 기존 프로젝트에 추가해주세요!
    - [x]  너무 쉬운 페이지가 아닌, UI 적으로 다양한 것을 도전할 수 있는 페이지를 만들어주세요!
    - [x]  팀원들과 스터디를 진행하며, 다른 스터디원이 만든 페이지를 보고 본인의 프로젝트에 1페이지 이상 구현해주세요!

### 🔍 접근 방법

- useMutation
