### ISSUE TITLE
[ Week 9 ] 9주차 워크북 미션1,2

### ISSUE THREAD

**Issue by heeone1** [DS-UMC-7th/UMC-7th-Wonie#27]
### 🛠 Mission

미션 1. redux-toolkit 활용 UMC PlayList 제작
미션 2. Modal Slice 활용하여, 모달 기능 추가

### 📝 To-do

미션 1. redux-toolkit 활용 UMC PlayList 제작
- [ ]  모든 스타일링을 `styled-components`를 활용해서 만들어주세요.
- [ ]  전역 상태 관리 라이브러리인 `redux-toolkit` 을 활용해서 만들어주세요.
- [ ]  `redux-toolkit`를 사용하기 위해서 `Provider`를 연결해주세요. (공식문서 참고)
- [ ]  `configureStore`를 활용해, 중앙 저장소를 만들어주세요!
- [ ]  cart에 관한 상태이니 `cartSlice`를 만들어주고, 중앙 저장소에 연결해주세요!
- [ ]  `음반수량 증가`시 해당하는 음반의 수량이 증가되게 `action` 함수를 만들어주세요. (**`increase action 기능 구현`**)
- [ ]  `음반수량 감소`시 해당하는 음반의 수량이 증가되게 `action` 함수를 만들어주세요. (**`decrease action 기능 구현`**)
- [ ]  음반 수량이 1보다 작아질 수 없지 않을까요? `1보다 작아진다면, 장바구니 목록에서 자동으로 제거`되게 만들어주세요. (**`removeItem action 기능 구현`**)
- [ ]  `장바구니 초기화` 버튼을 누르면 선택한 음반들이 다 제거되도록 위의 영상처럼 화면을 구성해 주세요! (**`clearCart action 기능 구현`**)
- [ ]  음반 수량 증가/감소 기능을 구현했습니다. 이를 바탕으로, 전체 금액이 얼마인지, 장바구니에 담고 있는 전체 수량이 몇 개인지, 계산해주는 action 함수를 만들어주세요. (**`calculateTotals action 기능 구현`**)

미션 2. Modal Slice 활용하여, 모달 기능 추가
- [ ]  **Cart Slice, Modal Slice 별도로 파일을 분리**하였는가?
- [ ]  Modal이 나오고, 아니요 버튼을 누르면 모달 창이 사라지는가?
- [ ]  Modal이 나오고, 네 버튼을 누르면 모든 쇼핑카트의 목록들이 제거 되고, 모달 창이 사라지는가?
- [ ]  이전 미션에서 만든 `clearCart Action`을 활용했는가?
- [ ]  Reducer를 활용해서 만들었는가? (`useState를 사용하지 않고, reducer`를 통해 만들어보세요! 제일 중요합니다!!)

### 🔍 접근 방법

- redux-toolkit
- Modal Slice
